config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),   
    path('userauth/', include('django.contrib.auth.urls')),    # built-in django auth
    path('userauth/', include('userauth.urls')),   
    path('accounts/', include('allauth.urls')),   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)          # url path reference for created media



# Configure Admin Titles
admin.site.site_header = "Events-App Admin Page"
admin.site.site_title = "Browser Lookup"
admin.site.index_title = "Welcome To Admin Dashboard"

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('<int:year>/<str:month>/', views.home, name='home'),
    path('', views.redirect_to_home, name='redirect-to-home'),
    path('events/', views.all_events, name='list-events'),
    path('venues/', views.list_venues, name='list-venues'),
    path('add_event/', views.add_event, name='add-event'),
    path('add_venue/', views.add_venue, name='add-venue'),    # path converters: int, str, path (whole urls/), slugs (hyphen-and_unerscores), UUID
    path('show_venue/<venue_id>/', views.show_venue, name='show-venue'),
    path('venue_events/<venue_id>', views.venue_events, name='venue-events'),
    path('search/', views.search, name='search'),
    path('update_venue/<venue_id>', views.update_venue, name='update-venue'),
    path('update_event/<event_id>', views.update_event, name='update-event'),
    path('delete_event/<event_id>', views.delete_event, name='delete-event'),
    path('delete_venue/<venue_id>', views.delete_venue, name='delete-venue'),
    path('venue_text', views.venue_text, name='venue-text'),
    path('venue_csv', views.venue_csv, name='venue-csv'),
    path('venue_pdf', views.venue_pdf, name='venue-pdf'),
    path('my_events', views.my_events, name='my-events'),
    path('join_event/<int:event_id>/', views.join_event, name='join-event'),
    path('leave_event/<int:event_id>/', views.leave_event, name='leave-event'),
    path('search_events', views.search_events, name='search-events'),
    path('admin_approval', views.admin_approval, name='admin-approval'),
    path('show_event/<event_id>/', views.show_event, name='show-event'),    
    path('privacy_policy/', views.privacy_policy, name='privacy-policy'),    
    path('terms_of_service/', views.terms_of_service, name='terms-of-service'),    
]

events/forms.py
from django import forms
from django.forms import ModelForm
from .models import Venue, ClubUser, Event

# User Event Form
class EventForm(ModelForm):
    class Meta:
        model = Event   
        fields = ('name', 'event_date', 'venue', 'attendees', 'description','event_image')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM',
            'venue': 'Venue',
            'attendees': 'Attendees',
            'description': '',
            'event_image': '',
        }
        widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Date'}),
            'venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            
        }

# Admin SuperUser Event Form
class AdminEventForm(ModelForm):
    class Meta:
        model = Event   
        fields = ('name', 'event_date', 'venue', 'manager', 'attendees', 'description', 'event_image')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM',
            'venue': 'Venue',
            'manager': 'Manager',
            'attendees': 'Attendees',
            'description': '',
            'event_image': '',
        }
        widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Date'}),
            'venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'manager': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Manager'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class VenueForm(ModelForm):
    class Meta:
        model = Venue   
        # fields = '__all__'
        fields = ('name', 'address', 'city_state', 'country', 'zip_code', 'phone', 'web', 'email_address', 'venue_image', 'owner')
        labels = {
            'name': '',
            'address': '',
            'city_state':'',
            'country':'',
            'zip_code': '',
            'phone': '',
            'web': '',
            'email_address': '',
            'venue_image':'',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Venue Name'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'city_state': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City/State'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'web': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Web Address'}),
            'email_address': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'owner': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue Owner'}),
        }

events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Count

import calendar
from calendar import HTMLCalendar
from datetime import datetime, timedelta
from django.utils import timezone

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse    # redirect_lazy change (redirect back to the page itself)
from .models import Event, Venue
from django.contrib.auth.models import User

from .forms import VenueForm, EventForm, AdminEventForm
from django.contrib import messages
import csv

# search / django-haystack
from django.db.models import Q


# pdf functionality modules
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import io 

# pagination
from django.core.paginator import Paginator


def terms_of_service(request):
    return render(request, 'events/terms_of_service.html')


def privacy_policy(request):
    return render(request, 'events/privacy_policy.html')


# Generate Venue PDF file
def venue_pdf(request):
    buf = io.BytesIO()                            # Create Bytestream buffer
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)       # Create canvas
    textobj = c.beginText()                       # Create text object 
    textobj.setTextOrigin(inch, inch)
    textobj.setFont("Helvetica", 14)

    venues = Venue.objects.all()
    lines = []

    for venue in venues:
        lines.append(venue.name)
        lines.append(venue.address)
        lines.append(venue.zip_code)
        lines.append(venue.phone)
        lines.append(venue.web)
        lines.append(venue.email_address)
        lines.append(" ")
    

    for line in lines:
        textobj.textLine(line)

    c.drawText(textobj)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='venue.pdf')


# Generate Venue CSV file
def venue_csv(request):
    response = HttpResponse(content_type='text/csv')

    response['Content-Disposition'] = 'attachment; filename=venues.csv'

    # create csv wrivter
    writer = csv.writer(response)

    # model designation
    venues = Venue.objects.all()

    # column headings to csv file
    writer.writerow(['Venue Name', 'Address', 'Zip Code', 'Phone', 'Web Address', 'Email'])


    for venue in venues:
        writer.writerow([venue.name, venue.address, venue.zip_code, venue.phone, venue.web, venue.email_address])

    
    return response 

# Generate Venue PDF file
def venue_text(request):
    response = HttpResponse(content_type='text/plain')
    # now = datetime.now()
    # current_year = now.year 

    response['Content-Disposition'] = 'attachment; filename=venues.txt'

    # model designation
    venues = Venue.objects.all()
    venue_catalog = ['Event-App \n', 'Current Venues: \n'] 
    
    for venue in venues:
        venue_catalog.append(f'{venue.name}\n{venue.address}\n{venue.zip_code}\n{venue.phone}\n{venue.web}\n{venue.email_address}\n\n\n')

    response.writelines(venue_catalog)
    return response 


@login_required
def leave_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.attendees.remove(request.user)
    event_name = event.name

    messages.success(request, (f"You have Unregistered from the '{event_name}' event..."))
    return redirect('events:show-event', event_id=event.id)




@login_required
def join_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.attendees.add(request.user)
    
    messages.success(request, ("You have Registered Successfully for this event..."))

    return redirect('events:show-event', event_id=event.id)



def my_events(request):
    if request.user.is_authenticated:
        user = request.user.id
        events = Event.objects.filter(attendees=user)
        has_events = events.exists()
        # managed_events = Event.objects.filter()

        return render(request, 'events/my_events.html', 
                      {"events":events,
                       "has_events": has_events})

    else:
        messages.success(request, ("You aren't Authorized to View this Page."))
        return redirect('events:list-events')
 


 
def search_events(request):
    if request.method == "POST":  
        searched = request.POST['searched']
        events = Event.objects.filter(description__contains=searched)      # query database for search

        return render(request, 'events/search_events.html', 
                      {'searched': searched,
                       'events': events})
    
    else: 
        return render(request, 'events/search_events.html', {})


def search(request):
    query = request.GET.get('q', '')
    if query:
        # Search in Event model
        events = Event.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
        # Search in Venue model
        venues = Venue.objects.filter(
            Q(name__icontains=query) |
            Q(address__icontains=query) |
            Q(zip_code__icontains=query)
        )
        return render(request, 'events/search_results.html', {'query': query, 'events': events, 'venues': venues})





def search_venues(request):    
    if request.method == "POST":  
        searched = request.POST['searched']
        
        # query database for search
        venues = Venue.objects.filter(name__contains=searched)

        return render(request, 'events/search_venues.html', 
                      {'searched': searched,
                       'venues': venues})
    
    else: 
        return render(request, 'events/search_venues.html', {})


def delete_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)
    venue.delete()
    messages.success(request, ("Venue Deleted!"))
    return redirect('events:list-venues')



def delete_event(request, event_id):
    event = Event.objects.get(pk=event_id)
  
    if request.user == event.manager:
        event.delete()
        messages.success(request, ("Event Deleted!"))
        return redirect('events:list-events')
    
    else:
        messages.success(request, ("You aren't Authorized to Delete This Event."))
        return redirect('events:list-events')


def update_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)  
    form = VenueForm(request.POST or None, request.FILES or None, instance=venue)
    
    if form.is_valid():
        form.save()
        return redirect('events:list-venues')

    return render(request, 'events/update_venue.html', 
                  {'venue': venue,
                   'form': form})


def update_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    if request.user.is_superuser:
        form = AdminEventForm(request.POST or None, request.FILES or None, instance=event)
    else:
        form = EventForm(request.POST or None, request.FILES or None, instance=event)

    if form.is_valid():
        form.save()
        return redirect('events:list-events')

    return render(request, 'events/update_event.html', 
                  {'event': event,
                   'form': form})


def show_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)

    venue_owner = Venue.owner     # venue owner query | non-primary model attribute alternative

    print(venue_owner)
    # Get events for particular venue
    events = venue.event_set.all()  

    return render(request, 'events/show_venue.html', 
                  {'venue': venue,
                   'venue_owner': venue_owner,
                   'events': events})


# Show Event
def show_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    
    event_list = Event.objects.all().order_by('event_date')

    event_with_attendee_count = Event.objects.annotate(num_attendees=Count('attendees'))
    attendee_count = event_with_attendee_count.count()

    return render(request, 'events/show_event.html', 
                  {"event": event,
                   "event_list": event_list,
                   "attendee_count": attendee_count})


# Events per Venue
def venue_events(request, venue_id):
    # Lookup venue
    venue = Venue.objects.get(id=venue_id)
    # Get venue events
    events = venue.event_set.all()           # grab events associated with venue (id)
    # events_list = Event.objects.filter(pk=venue_id)

    # print(f"THIS IS THE EVENT LIST LOG: {events_list}")


    if events:
        return render(request, 'events/venue_events.html', 
                      {"events": events})
    
    else:
        messages.success(request, ("That Venue Has No Events At This Time..."))
        return redirect('events:admin-approval')



def admin_approval(request):

    # Get venues
    venue_list = Venue.objects.all().order_by('name')

    # Get counts
    event_count = Event.objects.all().count()
    venue_count = Venue.objects.all().count()
    user_count = User.objects.all().count()

    event_list = Event.objects.all().order_by('-event_date')
    if request.user.is_superuser:
        if request.method == "POST":
            id_list = request.POST.getlist('boxes')     # get list with event_id of checked boxes (named 'boxes)
            # print(id_list)            # debugging log

            # Uncheck all events
            event_list.update(approved=False)
            
            # # Update database
            for i in id_list:
                Event.objects.filter(pk=int(i)).update(approved=True)       # updates approve to true, by filtering pk of event.id in box 

            # Shows success Message and Redirects to url
            messages.success(request, ('Event List Approval Updated.'))
            return redirect('events:list-events')
        
        else:
            return render(request, 'events/admin_approval.html', 

events/templates/events/admin_approval.html
{% extends 'base.html' %}

{% block content %}




{% if user.is_authenticated %}



        <div class="main-container">
            <h1>Admin Dashboard</h1>
  
            <form action="" method=POST>
                {% csrf_token %}

                <div class="main-header">
                    <div class="venue-events-box">
                        <!-- List Events by Venue -->
                        <table class="table table-striped table-hover table-bordered">
                            <thead>
                                <tr>
                                <th scope="col">Venue Name</th>
                                <th scope="col">Edit</th>
                                <th scope="col">Events</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for venue in venue_list %}
                                <tr>
                                    <td><a href="{% url 'events:show-venue' venue.id %}">{{venue}}</a></td>
                                    <td>
                                        <a href="{% url 'events:update-venue' venue.id %}" class="btn btn-outline-secondary btn-sm">Update</a>
                                                                          
                                        <!-- Button trigger modal -->
                                        <a href="#" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#staticBackdropDelete">Remove</a>                
                                        <!-- Modal -->
                                        <div class="modal fade" id="staticBackdropDelete" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">"{{ venue }}"</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                Are you sure you want to delete this Venue? 
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{% url 'events:delete-venue' venue.id %}" class="btn btn-outline-danger btn-sm">Delete Venue</a>
                                                <button type="button" class="btn btn-outline-primary btn-sm" data-bs-dismiss="modal">Cancel</button>
                                            </div>
                                            </div>
                                        </div>
                                        </div>

                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    </td>
                                    <td><a href="{% url 'events:venue-events' venue.id %}" class="btn btn-secondary">List Events</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>    
                    <div class="card-box">
                        <!-- Overall Counts -->
                        <div class="card">
                            <div class="card-header">
                                Overall Counts
                            </div>
                            <div class="card-body">
                                <p class="card-text">Event Count: {{event_count}}</p>
                                <p class="card-text">Venue Count: {{venue_count}}</p>
                                <p class="card-text">User Count: {{user_count}}</p>
                            </div>
                        </div>

                    </div>
                    
                </div>

                <hr>

                <div>
                    <!-- Event Approval form -->
                    <h2>Event Approval (Admin)</h2>
                    <br><br>
                    {% csrf_token %}
                    <table class="table table-stripped table-hover table-bordered border-primary">
                        <thead>
                        <tr>
                            <th scope="col">Event Name</th>
                            <th scope="col">Venue</th>
                            <th scope="col">Event Date</th>
                            <th scope="col">Manager</th>
                            <th scope="col">Approved</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for event in event_list %}
                            <tr>
                                <td>{{ event }}</td>
                                <td>{{ event.venue }}</td>
                                <td>{{ event.event_date }}</td>
                                <td>{{ event.manager }}</td>
                                <td>
                                    {% if event.approved %}
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" checked="checked" value={{event.id}} name="boxes">
                                        </div>
                                    {% else %}  
                                        <div class="form-check">
                                            <input type="checkbox" class="form-check-input" value={{event.id}} name="boxes">
                                        </div>
                                    {% endif %}
                                </td>
                            {% endfor %}
                            </tr>
                        </tbody>
                    </table>
                    <button class="btn btn-success" type="submit">Update Approval</button>
        
                </div>
            </form>
        </div>

        <br>


{% endif %}

{% endblock %}

events/templates/events/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      
<div class="main-header-box">
  <div class="welcome-box">

    <div class="jumbotron jumbotron-fluid">
      <div class="container">
        {% if user.is_authenticated %}
          <h1 class="display-4">Hello {{ user }}!</h1>
        {% else %}
        <h1 class="display-4">Welcome !</h1>
        {% endif %}
        
        <p class="lead">Welcome to <span id="welcome-span">EventHub</span>, an app show-casing basic event-management 
          features, authentication & OAuth, CRUD, permissions, admin dashboard, and more. Dive in! <br><br><strong>Disclaimer:</strong> this website is for educative and demonstrative purposes only. No actual events are posted on this website. 
        
        </p>
      </div>
    </div>  

    </div>
    <div class="flex-calendar-box">
      <img src="{% static '/img/eventhub-logo-png.png' %}" alt="eventhub-logo">
      <p>As of {{ time }}</p>
      <p>{{ cal | safe }}</p>
    </div>
  </div>
 

      {% if event_list %}

          <div class="date-paginator-bx">
              <h2>Events in: </h2>
              <div class="date-paginator" id="date-paginator">
                <a href="{% url 'events:home' prev_year prev_month %}"><i class="bi bi-arrow-left-circle"></i></a>
                <h2>{{ month }}</h2>
                <h2>{{ year }}</h2>
                <a href="{% url 'events:home' next_year next_month %}"><i class="bi bi-arrow-right-circle"></i></a>
              </div>
          </div>
                  
          <br><br>
          {% for event in event_list %}
          
          <div class="card">
            <div class="card-header" id="card-header-events">
              <h3>{{ event }}</h3>
            </div>
            <div class="card-body">
              <div class="flex-box">
                <div class="info-img-box">
                  <div class="info-box">
                    <h5 class="card-title">Venue: {{ event.venue }}</h5>
                    <p class="card-text">     
                      <ul>   
                          <li><span class="label">Date:</span> {{ event.event_date }}</li>
                          <li><span class="label">Days Until Event:</span> {{ event.days_until }} ( {{ event.is_past }} )</li>
                          {% if event.venue.web %}
                            <li><span class="label">Venue URL:</span><a href="{{ event.venue.web }}"> {{ event.venue.web }}</a></li>          
                          {% endif %}
                          <li><span class="label">Description:</span> {{ event.description }}</li>            
                          <br>
                      </ul>  
                    </p>  
                  </div>  
                  <div class="img-box">
                    {% if event.event_image %}
                      <img src="{{ event.event_image.url }}" alt="event-image">
                    {% else %}
                      <!-- Placeholder image or alternative content if no image is available -->
                      <p>No image available</p>
                    {% endif %}
                    </div>
                </div>
                      
              </div>                
                
            </div>
            <div class="card-footer text-muted"> 
              <div class="btn-bx">  
                <div>
                  {% if not user.is_authenticated %}
                    <a href="{% url 'login'%}" class="btn btn-outline-success btn-sm">Join Event</a>  
                  {% endif %}
    
                    <a href="{% url 'events:show-event' event.id %}" class="btn btn-outline-primary btn-sm">Show Event</a>
    
                    {% if user.is_authenticated and event.approved %} 
                      {% if user not in event.attendees.all and event.past == 'Pending' or user.is_superuser %}
                        <a href="{% url 'events:join-event' event.id %}" class="btn btn-outline-success btn-sm">Join Event</a>                 
    
                      {% elif user in event.attendees.all and event.past != 'Past' %}
                        <a href="{% url 'events:leave-event' event.id %}" class="btn btn-outline-danger btn-sm leave-btn">Leave Event</a>
                      {% endif %}
                    {% endif %}
                    {% if user.is_authenticated %}
                    {% if user == event.manager %}
                  
                        <a href="{% url 'events:update-event' event.id %}" class="btn btn-outline-secondary btn-sm">Update Event</a>
                        <a href="{% url 'events:delete-event' event.id %}" class="btn btn-outline-danger btn-sm">Delete Event</a>
                      
                    {% endif %}
                  {% endif %} 
                </div>
              </div>         
            </div>
          </div>
          <br><br>
          {% endfor %}
          <br><br>
      {% else %}
          <div class="date-paginator-bx">
              <h2>Events in: </h2>
              <div class="date-paginator" id="date-paginator">
                <a href="{% url 'events:home' prev_year prev_month %}"><i class="bi bi-arrow-left-circle"></i></a>
                <h2>{{ month }}</h2>
                <h2>{{ year }}</h2>
                <a href="{% url 'events:home' next_year next_month %}"><i class="bi bi-arrow-right-circle"></i></a>
              </div>
          </div>
          <h5>Sorry... there are no events this month</h5>
      {% endif %}

      <br><br><br>
</div>



{% endblock %}

events/templates/events/venues.html
{% extends 'base.html' %}

{% block content %}

    <div class="header-box">
        <div>
            <h1>Venues</h1>
        </div>
        <div class="file-download-box">
            <a href="{% url 'events:venue-csv' %}"><i class="bi bi-filetype-csv"></i></a>
            <a href="{% url 'events:venue-pdf' %}"><i class="bi bi-filetype-pdf"></i></a>
        </div>
    </div>
    
       
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for venue in venues %}
        <div class="col">
          <div class="card">
            {% if venue.venue_image %}
                <a href="{% url 'events:show-venue' venue.id %}"><img src="{{ venue.venue_image.url }}" class="card-img-top" width=500 alt="venue-image"></a>
            {% else %}
                <p>No image uploaded for this venue.</p>
            {% endif %}

            <div class="card-body">
              <h5 class="card-title">{{venue}}</h5>
              <p class="card-text">
                {{ venue.address }} {{ venue.city_state }}
              </p>
              <a href="{% url 'events:show-venue' venue.id %}" class="btn btn-outline-primary btn-sm">Read More</a>
                {% if user.is_authenticated %}
                    {% if user == venue_owner %}
                        <td align="right">
                            <a href="{% url 'events:update-venue' venue.id %}" class="btn btn-outline-secondary btn-sm">Update Venue</a>
                            <a href="{% url 'events:delete-venue' venue.id %}" class="btn btn-outline-danger btn-sm">Delete Venue</a>
                        </td>
                    {% endif %}
                {% endif %}
            </div>
          </div>
        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
        <!-- {{ venues }}<br> -->
        <!-- Has Previous: {{ venues.has_previous }}<br>
        Has Next: {{ venues.has_next }}<br>
        Current Page: {{ venues.number }}<br>
        Number of Pages: {{ venues.paginator.num_pages }}<br>  -->
    <hr>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if venues.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ venues.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for i in page_range %}
                <li class="page-item {% if i == venues.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                </li>
            {% endfor %}
            {% if venues.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ venues.next_page_number }}">Next</a></li>
                <li class="page-item"><a class="page-link" href="?page={{ venues.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>


{% endblock %} 