config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),   
    path('userauth/', include('django.contrib.auth.urls')),    # built-in django auth
    path('userauth/', include('userauth.urls')),   
    path('accounts/', include('allauth.urls')),   
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)          # url path reference for created media



# Configure Admin Titles
admin.site.site_header = "Events-App Admin Page"
admin.site.site_title = "Browser Lookup"
admin.site.index_title = "Welcome To Admin Dashboard"

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('<int:year>/<str:month>/', views.home, name='home'),
    path('', views.redirect_to_home, name='redirect-to-home'),
    path('events/', views.all_events, name='list-events'),
    path('venues/', views.list_venues, name='list-venues'),
    path('add_event/', views.add_event, name='add-event'),
    path('add_venue/', views.add_venue, name='add-venue'),    # path converters: int, str, path (whole urls/), slugs (hyphen-and_unerscores), UUID
    path('show_venue/<venue_id>/', views.show_venue, name='show-venue'),
    path('venue_events/<venue_id>', views.venue_events, name='venue-events'),
    path('search/', views.search, name='search'),
    path('update_venue/<venue_id>', views.update_venue, name='update-venue'),
    path('update_event/<event_id>', views.update_event, name='update-event'),
    path('delete_event/<event_id>', views.delete_event, name='delete-event'),
    path('delete_venue/<venue_id>', views.delete_venue, name='delete-venue'),
    path('venue_text', views.venue_text, name='venue-text'),
    path('venue_csv', views.venue_csv, name='venue-csv'),
    path('venue_pdf', views.venue_pdf, name='venue-pdf'),
    path('my_events', views.my_events, name='my-events'),
    path('join_event/<int:event_id>/', views.join_event, name='join-event'),
    path('leave_event/<int:event_id>/', views.leave_event, name='leave-event'),
    path('search_events', views.search_events, name='search-events'),
    path('admin_approval', views.admin_approval, name='admin-approval'),
    path('show_event/<event_id>/', views.show_event, name='show-event'),    
    path('privacy_policy/', views.privacy_policy, name='privacy-policy'),    
    path('terms_of_service/', views.terms_of_service, name='terms-of-service'),    
]

events/forms.py
from django import forms
from django.forms import ModelForm
from .models import Venue, ClubUser, Event

# User Event Form
class EventForm(ModelForm):
    class Meta:
        model = Event   
        fields = ('name', 'event_date', 'venue', 'attendees', 'description','event_image')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM',
            'venue': 'Venue',
            'attendees': 'Attendees',
            'description': '',
            'event_image': '',
        }
        widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Date'}),
            'venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
            
        }

# Admin SuperUser Event Form
class AdminEventForm(ModelForm):
    class Meta:
        model = Event   
        fields = ('name', 'event_date', 'venue', 'manager', 'attendees', 'description', 'event_image')
        labels = {
            'name': '',
            'event_date': 'YYYY-MM-DD HH:MM',
            'venue': 'Venue',
            'manager': 'Manager',
            'attendees': 'Attendees',
            'description': '',
            'event_image': '',
        }
        widgets = { 
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Name'}),
            'event_date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Event Date'}),
            'venue': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue'}),
            'manager': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Manager'}),
            'attendees': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Attendees'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description'}),
        }


class VenueForm(ModelForm):
    class Meta:
        model = Venue   
        # fields = '__all__'
        fields = ('name', 'address', 'city_state', 'country', 'zip_code', 'phone', 'web', 'email_address', 'venue_image', 'owner')
        labels = {
            'name': '',
            'address': '',
            'city_state':'',
            'country':'',
            'zip_code': '',
            'phone': '',
            'web': '',
            'email_address': '',
            'venue_image':'',
        }
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Venue Name'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Address'}),
            'city_state': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'City/State'}),
            'country': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Country'}),
            'zip_code': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Zip Code'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}),
            'web': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Web Address'}),
            'email_address': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'owner': forms.Select(attrs={'class': 'form-select', 'placeholder': 'Venue Owner'}),
        }

events/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Count

import calendar
from calendar import HTMLCalendar
from datetime import datetime, timedelta
from django.utils import timezone

from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse    # redirect_lazy change (redirect back to the page itself)
from .models import Event, Venue
from django.contrib.auth.models import User

from .forms import VenueForm, EventForm, AdminEventForm
from django.contrib import messages
import csv

# search / django-haystack
from django.db.models import Q


# pdf functionality modules
from django.http import FileResponse
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter
import io 

# pagination
from django.core.paginator import Paginator


def terms_of_service(request):
    return render(request, 'events/terms_of_service.html')


def privacy_policy(request):
    return render(request, 'events/privacy_policy.html')


# Generate Venue PDF file
def venue_pdf(request):
    buf = io.BytesIO()                            # Create Bytestream buffer
    c = canvas.Canvas(buf, pagesize=letter, bottomup=0)       # Create canvas
    textobj = c.beginText()                       # Create text object 
    textobj.setTextOrigin(inch, inch)
    textobj.setFont("Helvetica", 14)

    venues = Venue.objects.all()
    lines = []

    for venue in venues:
        lines.append(venue.name)
        lines.append(venue.address)
        lines.append(venue.zip_code)
        lines.append(venue.phone)
        lines.append(venue.web)
        lines.append(venue.email_address)
        lines.append(" ")
    

    for line in lines:
        textobj.textLine(line)

    c.drawText(textobj)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='venue.pdf')


# Generate Venue CSV file
def venue_csv(request):
    response = HttpResponse(content_type='text/csv')

    response['Content-Disposition'] = 'attachment; filename=venues.csv'

    # create csv wrivter
    writer = csv.writer(response)

    # model designation
    venues = Venue.objects.all()

    # column headings to csv file
    writer.writerow(['Venue Name', 'Address', 'Zip Code', 'Phone', 'Web Address', 'Email'])


    for venue in venues:
        writer.writerow([venue.name, venue.address, venue.zip_code, venue.phone, venue.web, venue.email_address])

    
    return response 

# Generate Venue PDF file
def venue_text(request):
    response = HttpResponse(content_type='text/plain')
    # now = datetime.now()
    # current_year = now.year 

    response['Content-Disposition'] = 'attachment; filename=venues.txt'

    # model designation
    venues = Venue.objects.all()
    venue_catalog = ['Event-App \n', 'Current Venues: \n'] 
    
    for venue in venues:
        venue_catalog.append(f'{venue.name}\n{venue.address}\n{venue.zip_code}\n{venue.phone}\n{venue.web}\n{venue.email_address}\n\n\n')

    response.writelines(venue_catalog)
    return response 


@login_required
def leave_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.attendees.remove(request.user)
    event_name = event.name

    messages.success(request, (f"You have Unregistered from the '{event_name}' event..."))
    return redirect('events:show-event', event_id=event.id)




@login_required
def join_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    event.attendees.add(request.user)
    
    messages.success(request, ("You have Registered Successfully for this event..."))

    return redirect('events:show-event', event_id=event.id)



def my_events(request):
    if request.user.is_authenticated:
        user = request.user.id
        events = Event.objects.filter(attendees=user)
        has_events = events.exists()
        # managed_events = Event.objects.filter()

        return render(request, 'events/my_events.html', 
                      {"events":events,
                       "has_events": has_events})

    else:
        messages.success(request, ("You aren't Authorized to View this Page."))
        return redirect('events:list-events')
 


 
def search_events(request):
    if request.method == "POST":  
        searched = request.POST['searched']
        events = Event.objects.filter(description__contains=searched)      # query database for search

        return render(request, 'events/search_events.html', 
                      {'searched': searched,
                       'events': events})
    
    else: 
        return render(request, 'events/search_events.html', {})


def search(request):
    query = request.GET.get('q', '')
    if query:
        # Search in Event model
        events = Event.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
        # Search in Venue model
        venues = Venue.objects.filter(
            Q(name__icontains=query) |
            Q(address__icontains=query) |
            Q(zip_code__icontains=query)
        )
        return render(request, 'events/search_results.html', {'query': query, 'events': events, 'venues': venues})





def search_venues(request):    
    if request.method == "POST":  
        searched = request.POST['searched']
        
        # query database for search
        venues = Venue.objects.filter(name__contains=searched)

        return render(request, 'events/search_venues.html', 
                      {'searched': searched,
                       'venues': venues})
    
    else: 
        return render(request, 'events/search_venues.html', {})


def delete_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)
    venue.delete()
    messages.success(request, ("Venue Deleted!"))
    return redirect('events:list-venues')



def delete_event(request, event_id):
    event = Event.objects.get(pk=event_id)
  
    if request.user == event.manager:
        event.delete()
        messages.success(request, ("Event Deleted!"))
        return redirect('events:list-events')
    
    else:
        messages.success(request, ("You aren't Authorized to Delete This Event."))
        return redirect('events:list-events')


def update_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)  
    form = VenueForm(request.POST or None, request.FILES or None, instance=venue)
    
    if form.is_valid():
        form.save()
        return redirect('events:list-venues')

    return render(request, 'events/update_venue.html', 
                  {'venue': venue,
                   'form': form})


def update_event(request, event_id):
    event = Event.objects.get(pk=event_id)
    if request.user.is_superuser:
        form = AdminEventForm(request.POST or None, request.FILES or None, instance=event)
    else:
        form = EventForm(request.POST or None, request.FILES or None, instance=event)

    if form.is_valid():
        form.save()
        return redirect('events:list-events')

    return render(request, 'events/update_event.html', 
                  {'event': event,
                   'form': form})


def show_venue(request, venue_id):
    venue = Venue.objects.get(pk=venue_id)

    venue_owner = Venue.owner     # venue owner query | non-primary model attribute alternative

    print(venue_owner)
    # Get events for particular venue
    events = venue.event_set.all()  

    return render(request, 'events/show_venue.html', 
                  {'venue': venue,
                   'venue_owner': venue_owner,
                   'events': events})


# Show Event
def show_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    
    event_list = Event.objects.all().order_by('event_date')

    event_with_attendee_count = Event.objects.annotate(num_attendees=Count('attendees'))
    attendee_count = event_with_attendee_count.count()

    return render(request, 'events/show_event.html', 
                  {"event": event,
                   "event_list": event_list,
                   "attendee_count": attendee_count})


# Events per Venue
def venue_events(request, venue_id):
    # Lookup venue
    venue = Venue.objects.get(id=venue_id)
    # Get venue events
    events = venue.event_set.all()           # grab events associated with venue (id)
    # events_list = Event.objects.filter(pk=venue_id)

    # print(f"THIS IS THE EVENT LIST LOG: {events_list}")


    if events:
        return render(request, 'events/venue_events.html', 
                      {"events": events})
    
    else:
        messages.success(request, ("That Venue Has No Events At This Time..."))
        return redirect('events:admin-approval')



def admin_approval(request):

    # Get venues
    venue_list = Venue.objects.all().order_by('name')

    # Get counts
    event_count = Event.objects.all().count()
    venue_count = Venue.objects.all().count()
    user_count = User.objects.all().count()

    event_list = Event.objects.all().order_by('-event_date')
    if request.user.is_superuser:
        if request.method == "POST":
            id_list = request.POST.getlist('boxes')     # get list with event_id of checked boxes (named 'boxes)
            # print(id_list)            # debugging log

            # Uncheck all events
            event_list.update(approved=False)
            
            # # Update database
            for i in id_list:
                Event.objects.filter(pk=int(i)).update(approved=True)       # updates approve to true, by filtering pk of event.id in box 

            # Shows success Message and Redirects to url
            messages.success(request, ('Event List Approval Updated.'))
            return redirect('events:list-events')
        
        else:
            return render(request, 'events/admin_approval.html', 

events/templates/partials/footer.html
<div class="b-example-divider"></div>

<div class="footer-bx">
    <div class="container" id="footer-bx">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item">
                    <a href="{% url 'events:home' year=gcurrent_year month=gcurrent_month %}" class="nav-link px-2 text-muted">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'events:privacy-policy' %}" class="nav-link px-2 text-muted">Privacy Policy</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'events:terms-of-service' %}" class="nav-link px-2 text-muted">Terms Of Service </a>
                </li>
                <!-- Button trigger modal -->
                <li class="nav-item">
                    <a href="#" class="nav-link px-2 text-muted" data-bs-toggle="modal" data-bs-target="#staticBackdrop">About</a>
                </li> 
                <li>
                    <a href="https://github.com/davidpal3c" class="nav-link px-2 text-muted" target="_blank"><i class="bi bi-github"></i></a>
                </li>
                <li>
                    <a href="https://www.linkedin.com/in/david-palacios-9077a2223/" class="nav-link px-2 text-muted" target="_blank"><i class="bi bi-linkedin"></i></a>
                </li>
                <!-- Modal -->
                <div class="modal fade" id="staticBackdrop" data-bs-keyboard="true" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">About EventHub</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        EventHub is an event-managing web application, demonstrating basic event-management features, authentication & OAuth, CRUD, permissions, admin dashboard, and file downloads. <br><br> Developed by David Palacios using Python, Django, PostgreSQL, Git, HTML & CSS, JavaScript, and Bootstrap5. 
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Ok!</button>
                      </div>
                    </div>
                  </div>
                </div>

            </ul>
            <p class="text-center text-muted">@Copyright <a href="mailto:davidpal3c@gmail.com?subject=eventHub-visitor inquiry">David P. (JaminPanda)</a></p>
        </footer>
    </div>
</div>

events/templates/partials/navbar.html
{% load static %}

    <nav class="navbar navbar-expand-lg navbar-dark navbar-dark bg-dark">
        <div class="container-fluid">
            <a href="{% url 'events:home' year=gcurrent_year month=gcurrent_month %}"><img src="{% static '/img/eventhub-logo-png.png' %}" alt="eventhub-logo"></a>
            <a href="{% url 'events:home' year=gcurrent_year month=gcurrent_month %}" class="navbar-brand">EventHub</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportContent" aria-controls="navbarSupportContent" aria-expanded="false" aria-lable="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-time">
                        <a href="{% url 'events:home' year=gcurrent_year month=gcurrent_month %}" class="nav-link">Calendar</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Events
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a href="{% url 'events:list-events' %}" class="dropdown-item">Show All Events</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'events:my-events' %}" class="dropdown-item">My Events</a></li>
                                <li><a href="{% url 'events:add-event' %}" class="dropdown-item">Add Event</a></li>
                            {% endif%}
                            <li><a href="{% url 'events:search-events' %}" class="dropdown-item">Search Events</a></li>
                        </ul>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Venues
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a href="{% url 'events:list-venues' %}" class="dropdown-item">Show All Venues</a></li>
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'events:add-venue' %}" class="dropdown-item">Add Venue</a></li>
                            {% endif %}
                        </ul>
                    </li>

                    <!-- Authentication access -->
                    {% if user.is_authenticated %}
                        {% if user.is_superuser %}
                            <li class="nav-item"><a href="{% url 'events:admin-approval' %}" class="nav-link">Admin Dashboard</a></li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'logout' %}" class="nav-link">Logout</a>
                        </li>
                        <li>
                            <p>{{user.username}}</p>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a href="{% url 'login' %}" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'register-user' %}" class="nav-link">Register</a>
                        </li>
                    {% endif %}
                        <li class="nav-item">
                            <a href="#" class="nav-link px-2" data-bs-toggle="modal" data-bs-target="#staticBackdrop">About</a>
                        </li> 

                        <!-- <li><a href="">{{ user }}</a></li> -->
                </ul>
                
                <!-- search field -->

                <form method="GET" action="{% url 'events:search' %}" class="d-flex">
                    <input type="search" class="form-control me-2" placeholder="Search" name="q" aria-label="Search">
                    <button type="Submit" class="btn btn-outline-secondary">Search</button>
                </form>
            </div>

        </div>

    </nav>